### ISSUE TITLE
No module named info.

### ISSUE THREAD

**Issue by bweston92** [mysql/mysql-utilities#11]
Attempting to install but not able to continue as no module named "info" is available. I've tried searching Google etc but found nothing. Any ideas?

```
$ python --version
Python 2.7.11

$ pip install mysql-utilities
Collecting mysql-utilities
  Using cached mysql-utilities-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tRgO2D/mysql-utilities/setup.py", line 36, in <module>
        from info import META_INFO, INSTALL
    ImportError: No module named info

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tRgO2D/mysql-utilities/
```

**Comment by matthewbogner** [comment]
I know this is a pretty old issue.  But figured I would post here for the benefit of others.  It seems this python module requires python 3.   After switching to python 3 it seems to work.

**Comment by ShahriyarR** [comment]
Same for me but with different error:

```
/opt/Python-3.5.3/bin/pip3 install mysql-utilities
Collecting mysql-utilities
  Downloading mysql-utilities-1.4.3.tar.gz (564kB)
    100% |████████████████████████████████| 573kB 247kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-om1j5ovh/mysql-utilities/setup.py", line 21, in <module>
        import ConfigParser
    ImportError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-om1j5ovh/mysql-utilities/
```

**Comment by imami** [comment]
I have faced the same problem.

**Comment by ShahriyarR** [comment]
I have reported this as bug and it is verified:

https://bugs.mysql.com/bug.php?id=85108

**Comment by mortymacs** [comment]
It could be installed manually by `python setup.py install`

**Comment by imami** [comment]
@ShahriyarR : 

Thanks to @mortezaipo , we've installed it using [release-1.6.5](https://github.com/mysql/mysql-utilities/releases/tag/release-1.6.5) and everything goes fine and safe.

**Comment by gopisaluja-bst** [comment]
@mortymacs from where i can get setup.py?

**Comment by mortymacs** [comment]
> @mortymacs from where i can get setup.py?

It's in the root of the project. Download the project, extract it, and then run the command.

**Comment by gopisaluja-bst** [comment]
@mortymacs not working with python3

**Comment by mortymacs** [comment]
> @mortymacs not working with python3

In the setup.py (in master branch), they mentioned it only works with Python 2.6 or 2.7:
> MySQL Utilities requires Python v2.6 or v2.7
https://github.com/mysql/mysql-utilities/blob/master/setup.py#L39-L41
